<Workspace Version="1.3.0.875" X="-494.365775770019" Y="-502.225748732276" zoom="2.38374849738754" ScaleFactor="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <CoreNodeModels.Watch guid="75e03f13-1650-4b62-baef-f895ed73c0ee" type="CoreNodeModels.Watch" nickname="Watch" x="542.647989444332" y="296.927503573691" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <DSRevitNodesUI.FloorTypes guid="e2614b3b-a395-4541-85c3-ae8c9980761b" type="DSRevitNodesUI.FloorTypes" nickname="Floor Types" x="311.696874535793" y="297.44207476418" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="2:Generic 150mm" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e2614b3b-a395-4541-85c3-ae8c9980761b" start_index="0" end="75e03f13-1650-4b62-baef-f895ed73c0ee" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-10.3516321182251" eyeY="13.9155826568604" eyeZ="16.0006294250488" lookX="16.1289100646973" lookY="-8.16507530212402" lookZ="-20.5040168762207" upX="0.0538851283490658" upY="0.996194660663605" upZ="-0.0685019418597221" />
  </Cameras>
</Workspace>