<Workspace Version="1.3.0.875" X="-427.986401811757" Y="-345.647101947193" zoom="2.0686261415142" ScaleFactor="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <DSRevitNodesUI.StructuralFramingTypes guid="699bface-e3db-449a-9916-4b3a3d7563b6" type="DSRevitNodesUI.StructuralFramingTypes" nickname="Structural Framing Types" x="305.296874535793" y="297.44207476418" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="3:356mm" />
    <CoreNodeModels.Watch guid="74b70737-cc11-4999-8a2c-b458c617cdfe" type="CoreNodeModels.Watch" nickname="Watch" x="561.372472148489" y="297.44207476418" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="699bface-e3db-449a-9916-4b3a3d7563b6" start_index="0" end="74b70737-cc11-4999-8a2c-b458c617cdfe" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-10.3516321182251" eyeY="13.9155826568604" eyeZ="16.0006294250488" lookX="16.1289100646973" lookY="-8.16507530212402" lookZ="-20.5040168762207" upX="0.0538851283490658" upY="0.996194660663605" upZ="-0.0685019418597221" />
  </Cameras>
</Workspace>