<Workspace Version="1.1.0.2093" X="-2412.37897105527" Y="-3865.56450172977" zoom="1.17828125946571" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Rectangle" resolvedName="Autodesk.DesignScript.Geometry.Rectangle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Surface" resolvedName="Autodesk.DesignScript.Geometry.Surface" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Sphere" resolvedName="Autodesk.DesignScript.Geometry.Sphere" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Cylinder" resolvedName="Autodesk.DesignScript.Geometry.Cylinder" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Line" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="PolySurface" resolvedName="Autodesk.DesignScript.Geometry.PolySurface" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="42d5ff37-f86e-44f4-bad3-8cc80a511874" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2720.11279024856" y="3375.31846280258" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
solid = IN[0]
seed = IN[1]
xCount = IN[2]
yCount = IN[3]

solids = []
crvs = []

edges = solid.Edges
for edge in edges:
	crvs.append(edge.CurveGeometry)
	
bbox = BoundingBox.ByGeometry(crvs)
yDist = bbox.MaxPoint.Y-bbox.MinPoint.Y
xDist = bbox.MaxPoint.X-bbox.MinPoint.X

xRange = list(range(xCount))
yRange = list(range(yCount))

fromCoord = solid.ContextCoordinateSystem
 
#Loop through X and Y
for i in xRange:
	for j in yRange:
		#Rotate and translate the coordinate system
		toCoord = fromCoord.Rotate(solid.ContextCoordinateSystem.Origin,Vector.ByCoordinates(0,0,1),(90*(i+j%seed)))
		vec = Vector.ByCoordinates((xDist*i),(yDist*j),0)
		toCoord = toCoord.Translate(vec)
		#Transform the solid from the source coordinate system to the target coordinate system and append to the list
		solids.append(solid.Transform(fromCoord,toCoord))


#Assign your output to the OUT variable.
OUT = solids
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="6419d5bc-9623-4038-93e9-446ef6e283c5" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2603.66950218039" y="3425.55607107903" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="3;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="6a64025a-a52f-4652-8d89-6db24157c2a9" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2603.66950218039" y="3509.11275371931" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="10;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="7e2539d8-64a4-4ed0-b606-c6c8bbd89b1f" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Cuboid.ByCorners" x="2203.79190990326" y="3292.60178477953" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Cuboid.ByCorners@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="33da645f-db71-4d4f-836a-95a127129fa6" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.Rotate" x="2414.09556068331" y="3375.31846280258" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Rotate@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector,double">
      <PortInfo index="3" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="83a112f1-7427-46ef-a201-aaf177aca6fc" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.Origin" x="2282.99190990326" y="3402.22386524679" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.Origin" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="c6c66d8d-54cc-4f75-86c2-0bd8d223b618" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2288.59190990326" y="3570.2680261813" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="10;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="3156e855-224c-4c62-b83d-3adf7651cfd4" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2063.79190990326" y="3486.24594571404" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Vector.ByCoordinates(1,0.5,0.5);" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6419d5bc-9623-4038-93e9-446ef6e283c5" start_index="0" end="42d5ff37-f86e-44f4-bad3-8cc80a511874" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6a64025a-a52f-4652-8d89-6db24157c2a9" start_index="0" end="42d5ff37-f86e-44f4-bad3-8cc80a511874" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6a64025a-a52f-4652-8d89-6db24157c2a9" start_index="0" end="42d5ff37-f86e-44f4-bad3-8cc80a511874" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7e2539d8-64a4-4ed0-b606-c6c8bbd89b1f" start_index="0" end="33da645f-db71-4d4f-836a-95a127129fa6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="33da645f-db71-4d4f-836a-95a127129fa6" start_index="0" end="42d5ff37-f86e-44f4-bad3-8cc80a511874" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="83a112f1-7427-46ef-a201-aaf177aca6fc" start_index="0" end="33da645f-db71-4d4f-836a-95a127129fa6" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c6c66d8d-54cc-4f75-86c2-0bd8d223b618" start_index="0" end="33da645f-db71-4d4f-836a-95a127129fa6" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3156e855-224c-4c62-b83d-3adf7651cfd4" start_index="0" end="33da645f-db71-4d4f-836a-95a127129fa6" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="0.467936557756604" eyeY="15.5737146089602" eyeZ="4.06258744115851" lookX="0.0272772301992837" lookY="-10.4702163303049" lookZ="-7.8143385653858" upX="0.00107866860260274" upY="0.951056478829832" upZ="-0.309015104333053" />
  </Cameras>
</Workspace>