<Workspace Version="1.3.0.875" X="-187.797172769894" Y="-405.813706569405" zoom="2.02214559402288" ScaleFactor="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Color" resolvedName="DSCore.Color" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e4e5d3c0-1190-4236-84d7-e26ef9b8632d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Document.Current" x="238.907026784531" y="329.921607434369" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Application.Document.Current" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="95f8961e-5657-4f91-9285-a615e6216e07" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Document.IsFamilyDocument" x="419.006943455702" y="329.921607434369" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Application.Document.IsFamilyDocument">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e4e5d3c0-1190-4236-84d7-e26ef9b8632d" start_index="0" end="95f8961e-5657-4f91-9285-a615e6216e07" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-10.3516321182251" eyeY="13.9155826568604" eyeZ="16.0006294250488" lookX="16.1289100646973" lookY="-8.16507530212402" lookZ="-20.5040168762207" upX="0.0538851283490658" upY="0.996194660663605" upZ="-0.0685019418597221" />
  </Cameras>
</Workspace>