<Workspace Version="1.1.0.2093" X="749.326350559705" Y="-5329.90689548734" zoom="1.90479712435349" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Color" resolvedName="DSCore.Color" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Display" resolvedName="Display.Display" assemblyName="Display.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9222260d-0749-4abb-b34a-20af71030c41" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.ExtrudeAsSolid" x="-160.122289761206" y="2817.235439445" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.ExtrudeAsSolid@double">
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="30a8c0ff-c030-4a5b-9119-3a44ccc5f608" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Circle.ByCenterPointRadius" x="-375.597933231544" y="2817.235439445" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Circle.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="1c8aa736-6a38-47ed-ac7c-d1805582c1a2" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.SerializeAsSAB" x="26.5533537091324" y="2817.235439445" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.SerializeAsSAB@Autodesk.DesignScript.Geometry.Geometry[]" />
    <CoreNodeModels.Watch guid="0d7eacf6-814d-4943-98ab-6534e2e2174c" type="CoreNodeModels.Watch" nickname="Watch" x="230.828997179471" y="2817.235439445" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="9222260d-0749-4abb-b34a-20af71030c41" start_index="0" end="1c8aa736-6a38-47ed-ac7c-d1805582c1a2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="30a8c0ff-c030-4a5b-9119-3a44ccc5f608" start_index="0" end="9222260d-0749-4abb-b34a-20af71030c41" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1c8aa736-6a38-47ed-ac7c-d1805582c1a2" start_index="0" end="0d7eacf6-814d-4943-98ab-6534e2e2174c" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-0.52827745624646" eyeY="3.02701066701207" eyeZ="3.89860494191523" lookX="3.35059157229383" lookY="-4.38075048042917" lookZ="-7.45910604699377" upX="0.111567849969459" upY="0.9622179571921" upZ="-0.248372991165857" />
  </Cameras>
</Workspace>