<Workspace Version="1.1.0.2093" X="-903.904170049268" Y="-384.89533184749" zoom="1.33157928308587" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Color" resolvedName="DSCore.Color" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Display" resolvedName="Display.Display" assemblyName="Display.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="7a59348b-af42-4db7-b4d1-fc8423f52ffa" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Cuboid.ByCorners" x="958.431721300605" y="417.272580401128" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Cuboid.ByCorners@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <CoreNodeModels.Watch guid="abe0c77f-86f2-4ed9-8aa8-685134ba6434" type="CoreNodeModels.Watch" nickname="Watch" x="1331.80767929071" y="417.272580401128" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9135ec7b-2487-4253-925b-b5043b6183b2" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Topology.Edges" x="1149.11970029566" y="417.272580401128" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Topology.Edges" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="8eab14c9-fedc-4094-8bb1-6576a3669151" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Edge.CurveGeometry" x="1642.69429174587" y="416.994939457338" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Edge.CurveGeometry" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="e1e7d204-e43a-4d2f-8471-94e3557e5c43" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1150.79146648987" y="320.051726186369" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="color = Color.ByARGB(100,141,198,217);&#xA;Display.ByGeometryColor(geometry, color);" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7a59348b-af42-4db7-b4d1-fc8423f52ffa" start_index="0" end="9135ec7b-2487-4253-925b-b5043b6183b2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7a59348b-af42-4db7-b4d1-fc8423f52ffa" start_index="0" end="e1e7d204-e43a-4d2f-8471-94e3557e5c43" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="abe0c77f-86f2-4ed9-8aa8-685134ba6434" start_index="0" end="8eab14c9-fedc-4094-8bb1-6576a3669151" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9135ec7b-2487-4253-925b-b5043b6183b2" start_index="0" end="abe0c77f-86f2-4ed9-8aa8-685134ba6434" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-0.32769864310709" eyeY="1.51630279563463" eyeZ="2.04072197694941" lookX="6.029801942626" lookY="-2.73845751362288" lookZ="-7.42248317756825" upX="0.0395914241671562" upY="0.998026669025421" upZ="-0.0487357005476952" />
  </Cameras>
</Workspace>