<Workspace Version="1.2.1.3083" X="-1350.38644088658" Y="-221.067135646009" zoom="2.0806391859999" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Color" resolvedName="DSCore.Color" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <DSRevitNodesUI.RevitPhases guid="02a2f2f6-0234-4c5d-b85f-42e0077edac4" type="DSRevitNodesUI.RevitPhases" nickname="Select Phase" x="740.712033088978" y="260.225405725892" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true" index="-1" />
    <DSRevitNodesUI.RevitPhases guid="8104b046-a195-4384-b513-64ec0aff53e7" type="DSRevitNodesUI.RevitPhases" nickname="Select Phase" x="928.661130341254" y="260.225405725892" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true" index="-1" />
    <DSRevitNodesUI.RevitPhases guid="d0bd8521-2e76-41ec-a13b-5462f634a538" type="DSRevitNodesUI.RevitPhases" nickname="Select Phase" x="1116.61022759353" y="260.225405725892" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true" index="-1" />
  </Elements>
  <Connectors />
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-10.3516321182251" eyeY="13.9155826568604" eyeZ="16.0006294250488" lookX="16.1289100646973" lookY="-8.16507530212402" lookZ="-20.5040168762207" upX="0.0538851283490658" upY="0.996194660663605" upZ="-0.0685019418597221" />
  </Cameras>
</Workspace>