<Workspace Version="1.2.1.3083" X="-617.237643902607" Y="-363.038443763944" zoom="1.27829901769395" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Color" resolvedName="DSCore.Color" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5cbda049-923d-4b63-a9da-04ca886eaef4" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Grid.Curve" x="946.970167437655" y="560.442685265549" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Grid.Curve">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <DSRevitNodesUI.ElementTypes guid="4a726187-d9fc-4663-8d30-f2ea00ddbc6b" type="DSRevitNodesUI.ElementTypes" nickname="Element Types" x="543.053069890337" y="560.442685265549" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="142:Grid" />
    <DSRevitNodesUI.ElementsOfType guid="59827eb9-1ac9-4de0-91d7-40358f027070" type="DSRevitNodesUI.ElementsOfType" nickname="All Elements of Type" x="721.411618663996" y="560.442685265549" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfType>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="4a726187-d9fc-4663-8d30-f2ea00ddbc6b" start_index="0" end="59827eb9-1ac9-4de0-91d7-40358f027070" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="59827eb9-1ac9-4de0-91d7-40358f027070" start_index="0" end="5cbda049-923d-4b63-a9da-04ca886eaef4" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-2117.89553431788" eyeY="26516.6371752573" eyeZ="26144.1436387024" lookX="-2493.55486430866" lookY="-38606.2820345739" lookZ="-18178.3065464297" upX="-0.107381608000919" upY="0.612907029898675" upZ="-0.782824429865558" />
  </Cameras>
</Workspace>