<Workspace Version="1.2.1.3083" X="-583.33148254133" Y="-589.117396870051" zoom="1.47684812280381" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Color" resolvedName="DSCore.Color" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <DSRevitNodesUI.ElementTypes guid="4a726187-d9fc-4663-8d30-f2ea00ddbc6b" type="DSRevitNodesUI.ElementTypes" nickname="Element Types" x="543.053069890337" y="560.442685265549" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="142:Grid" />
    <DSRevitNodesUI.ElementsOfType guid="59827eb9-1ac9-4de0-91d7-40358f027070" type="DSRevitNodesUI.ElementsOfType" nickname="All Elements of Type" x="721.411618663996" y="560.442685265549" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfType>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a12f6f8b-6cd6-44ac-9c10-a1dbc0df976c" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Grid.ElementCurveReference" x="948.230950849498" y="560.442685265549" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Grid.ElementCurveReference">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="4a726187-d9fc-4663-8d30-f2ea00ddbc6b" start_index="0" end="59827eb9-1ac9-4de0-91d7-40358f027070" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="59827eb9-1ac9-4de0-91d7-40358f027070" start_index="0" end="a12f6f8b-6cd6-44ac-9c10-a1dbc0df976c" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-10.3516321182251" eyeY="13.9155826568604" eyeZ="16.0006294250488" lookX="16.1289100646973" lookY="-8.16507530212402" lookZ="-20.5040168762207" upX="0.0538851283490658" upY="0.996194660663605" upZ="-0.0685019418597221" />
  </Cameras>
</Workspace>