<Workspace Version="1.3.0.875" X="-171.918793679806" Y="-414.009574816415" zoom="1.33823125" ScaleFactor="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9eac7507-3fdc-4779-b89c-9e1b0cd8b530" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="CurtainPanel.ByElement" x="383.615550755939" y="453" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.CurtainPanel.ByElement@Revit.Elements.Element">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Nodes.DSModelElementSelection guid="668aaa46-d679-4f53-a4c0-5c9c5e6d4778" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="184.541036717062" y="453" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="98e2f96c-ccbd-4abb-a697-e7e5136106ee-000cec5b" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="afa76d2d-0bf6-4792-b583-9d278080c135" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="CurtainPanel.SupportingMullions" x="716.52807775378" y="453" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.CurtainPanel.SupportingMullions">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="0dd5689e-c6fc-447b-aaa9-991b735d1bea" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Mullion.LocationCurve" x="1007.5" y="453" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Mullion.LocationCurve">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="9eac7507-3fdc-4779-b89c-9e1b0cd8b530" start_index="0" end="afa76d2d-0bf6-4792-b583-9d278080c135" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="668aaa46-d679-4f53-a4c0-5c9c5e6d4778" start_index="0" end="9eac7507-3fdc-4779-b89c-9e1b0cd8b530" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="afa76d2d-0bf6-4792-b583-9d278080c135" start_index="0" end="0dd5689e-c6fc-447b-aaa9-991b735d1bea" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-10.3516321182251" eyeY="13.9155826568604" eyeZ="16.0006294250488" lookX="16.1289100646973" lookY="-8.16507530212402" lookZ="-20.5040168762207" upX="0.0538851283490658" upY="0.996194660663605" upZ="-0.0685019418597221" />
  </Cameras>
</Workspace>