<Workspace Version="1.3.0.875" X="163.209145603125" Y="-474.057972907613" zoom="1.545620359375" ScaleFactor="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3f6e0693-b2d1-4ff3-a4c6-ce95dd86d9c5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Category.ByName" x="450.5" y="494" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Category.ByName@string">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="306da2cc-65f6-443d-80fb-3ea53e9e5014" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="72" y="466" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="sc = &quot;Structural Columns&quot;;&#xA;sf = &quot;Structural Foundations&quot;;&#xA;fl = &quot;Floors&quot;;&#xA;wa = &quot;Walls&quot;;&#xA;rf = &quot;Roofs&quot;;&#xA;{sc, sf, fl, wa, rf};" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="306da2cc-65f6-443d-80fb-3ea53e9e5014" start_index="5" end="3f6e0693-b2d1-4ff3-a4c6-ce95dd86d9c5" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-10.3516321182251" eyeY="13.9155826568604" eyeZ="16.0006294250488" lookX="16.1289100646973" lookY="-8.16507530212402" lookZ="-20.5040168762207" upX="0.0538851283490658" upY="0.996194660663605" upZ="-0.0685019418597221" />
  </Cameras>
</Workspace>