<Workspace Version="1.0.0.1180" X="101.267427645615" Y="80.9890364772989" zoom="1.02988563947099" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="8275635b-e59d-4cc3-be97-f6d16efe5cdf" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.SweepAsSurface" x="687.456289202846" y="7.94570837690338" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.SweepAsSurface@Autodesk.DesignScript.Geometry.Curve" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="226953a7-69e6-48b7-b226-983727ca1cad" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Line.ByStartPointEndPoint" x="462.025408397713" y="88.3447005114569" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="b05e3ae1-28b9-4e6a-82ff-7e3139d466ca" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="158.499495411681" y="96.3447005114569" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Point.Origin();&#xA;Point.ByCoordinates(10,0,0);" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="b2eeff6b-e3eb-46c7-b732-3a0c539a5e8a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Arc.ByThreePoints" x="471.625408397713" y="-51.7219004442438" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Arc.ByThreePoints@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="555ea511-e4a3-461c-ab71-ed573084dd12" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="158.499495411681" y="-39.7219004442438" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Point.Origin();&#xA;Point.ByCoordinates(0,5,3);&#xA;Point.ByCoordinates(0,10,0);" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="226953a7-69e6-48b7-b226-983727ca1cad" start_index="0" end="8275635b-e59d-4cc3-be97-f6d16efe5cdf" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b05e3ae1-28b9-4e6a-82ff-7e3139d466ca" start_index="0" end="226953a7-69e6-48b7-b226-983727ca1cad" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b05e3ae1-28b9-4e6a-82ff-7e3139d466ca" start_index="1" end="226953a7-69e6-48b7-b226-983727ca1cad" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b2eeff6b-e3eb-46c7-b732-3a0c539a5e8a" start_index="0" end="8275635b-e59d-4cc3-be97-f6d16efe5cdf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="555ea511-e4a3-461c-ab71-ed573084dd12" start_index="0" end="b2eeff6b-e3eb-46c7-b732-3a0c539a5e8a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="555ea511-e4a3-461c-ab71-ed573084dd12" start_index="1" end="b2eeff6b-e3eb-46c7-b732-3a0c539a5e8a" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="555ea511-e4a3-461c-ab71-ed573084dd12" start_index="2" end="b2eeff6b-e3eb-46c7-b732-3a0c539a5e8a" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-12.151876449585" eyeY="10.257155418396" eyeZ="4.30262565612793" lookX="16.0185146331787" lookY="-5.66828918457031" lookZ="-8.91968441009521" upX="0.0731078237295151" upY="0.996492862701416" upZ="-0.040709063410759" />
  </Cameras>
</Workspace>