<Workspace Version="1.1.0.2093" X="-282.402869886197" Y="-2041.63766367635" zoom="1.4517389755498" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Circle" resolvedName="Autodesk.DesignScript.Geometry.Circle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Geometry" resolvedName="Autodesk.DesignScript.Geometry.Geometry" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector.ZAxis" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="NurbsSurface" resolvedName="Autodesk.DesignScript.Geometry.NurbsSurface" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Sphere" resolvedName="Autodesk.DesignScript.Geometry.Sphere" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a92a46eb-dd18-4932-9b2c-c72617290d3a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Object.Identity" x="810.57401748339" y="1416.21529967652" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.Object.Identity@var" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="01aabf49-1e04-4345-ba82-f1b733687cc4" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Object.Identity" x="810.57401748339" y="1511.89185032106" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.Object.Identity@var" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a0d2ab24-f797-4c02-b27e-176e1306404c" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Object.Identity" x="810.57401748339" y="1607.5684009656" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.Object.Identity@var" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="c2000a1e-4e57-46a1-8966-c1ebe1290c77" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="215.501741353093" y="1481.22224016603" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="pt=Point.ByCoordinates(4,0);&#xA;&#xA;circle=Circle.ByCenterPointRadius(Point.ByCoordinates(-2,0));&#xA;&#xA;sphere=Sphere.ByCenterPointRadius(Point.ByCoordinates(1,0));" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="c2000a1e-4e57-46a1-8966-c1ebe1290c77" start_index="0" end="a92a46eb-dd18-4932-9b2c-c72617290d3a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c2000a1e-4e57-46a1-8966-c1ebe1290c77" start_index="1" end="01aabf49-1e04-4345-ba82-f1b733687cc4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c2000a1e-4e57-46a1-8966-c1ebe1290c77" start_index="2" end="a0d2ab24-f797-4c02-b27e-176e1306404c" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="0.31794312305281" eyeY="6.24162907639478" eyeZ="2.92445446209934" lookX="0.00739818210676935" lookY="-7.24252129503874" lookZ="-4.74306723491498" upX="0.00109132574960712" upY="0.714472683463458" upZ="-0.699662519638404" />
  </Cameras>
</Workspace>