<Workspace Version="1.3.0.875" X="5.63690414062501" Y="-499.4641773125" zoom="1.545620359375" ScaleFactor="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a356618f-c9f5-490b-9db5-e7f743d0712a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Material.ByName" x="410.5" y="481" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Material.ByName@string">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="2a829480-84e2-4474-80f1-699e593ffefb" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="71" y="436" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="conc = &quot;Concrete, Cast In Situ&quot;;&#xA;co = &quot;Copper&quot;;&#xA;df = &quot;Default Floor&quot;;&#xA;gt = &quot;Glass - Transparent&quot;;&#xA;{conc, co, df, gt};" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="107bd415-ce93-47eb-84d8-bd8a4ef2cc11" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Material.SurfacePatternColor" x="645.9" y="481" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Material.SurfacePatternColor">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="a356618f-c9f5-490b-9db5-e7f743d0712a" start_index="0" end="107bd415-ce93-47eb-84d8-bd8a4ef2cc11" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2a829480-84e2-4474-80f1-699e593ffefb" start_index="4" end="a356618f-c9f5-490b-9db5-e7f743d0712a" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-10.3516321182251" eyeY="13.9155826568604" eyeZ="16.0006294250488" lookX="16.1289100646973" lookY="-8.16507530212402" lookZ="-20.5040168762207" upX="0.0538851283490658" upY="0.996194660663605" upZ="-0.0685019418597221" />
  </Cameras>
</Workspace>