<Workspace Version="1.0.0.1180" X="-403.671123827002" Y="-667.501466533396" zoom="0.93960835564511" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <CoreNodeModels.Input.DoubleSlider guid="d1cb45b7-1e5f-4ef9-b6da-7c41293897a6" type="CoreNodeModels.Input.DoubleSlider" nickname="Number Slider" x="550.481983567209" y="837.341060714802" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Double>6.8</System.Double>
      <Range min="0" max="100" step="0.1" />
    </CoreNodeModels.Input.DoubleSlider>
    <CoreNodeModels.Input.DoubleSlider guid="986b2b32-a077-4e02-81b5-d987ba13d0ea" type="CoreNodeModels.Input.DoubleSlider" nickname="Number Slider" x="550.481983567209" y="901.821493897852" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Double>2.7</System.Double>
      <Range min="0" max="100" step="0.1" />
    </CoreNodeModels.Input.DoubleSlider>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9ca64c4a-9067-431f-8bfc-c8c3e4271867" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Rectangle.ByWidthLength" x="1064.97860154654" y="750.186920343878" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength@Autodesk.DesignScript.Geometry.Plane,double,double">
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a1f1fbb2-9797-4af8-8ea9-603fec255212" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Plane.YZ" x="772.881983567209" y="750.186920343878" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Plane.YZ" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d1cb45b7-1e5f-4ef9-b6da-7c41293897a6" start_index="0" end="9ca64c4a-9067-431f-8bfc-c8c3e4271867" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="986b2b32-a077-4e02-81b5-d987ba13d0ea" start_index="0" end="9ca64c4a-9067-431f-8bfc-c8c3e4271867" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a1f1fbb2-9797-4af8-8ea9-603fec255212" start_index="0" end="9ca64c4a-9067-431f-8bfc-c8c3e4271867" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-4.7700603973704" eyeY="4.43560491599612" eyeZ="6.02526280959179" lookX="5.16574737328125" lookY="-3.69081382359375" lookZ="-5.13171319828125" upX="0.177629590034485" upY="0.9681476354599" upZ="-0.176459282636642" />
  </Cameras>
</Workspace>