<Workspace Version="1.3.0.875" X="-252.088989230089" Y="-856.448225009067" zoom="1.34613730474457" ScaleFactor="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <DSRevitNodesUI.ElementTypes guid="bca29ce5-ce63-4eff-bd07-9c238fe43f2c" type="DSRevitNodesUI.ElementTypes" nickname="Element Types" x="211.783942997935" y="843.873024506583" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="312:TextNote" />
    <DSRevitNodesUI.ElementsOfType guid="a2236413-456b-482f-8f3c-010930df5503" type="DSRevitNodesUI.ElementsOfType" nickname="All Elements of Type" x="381.89991829204" y="843.873024506583" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfType>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="39739145-650e-4bf9-bb60-4174a90b494b" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="TextNote.SetKeepRotatedTextReadable" x="611.719755876082" y="843.873024506583" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.TextNote.SetKeepRotatedTextReadable@bool">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <CoreNodeModels.Input.BoolSelector guid="fdbafaad-160f-4c6a-b444-fdb676379957" type="CoreNodeModels.Input.BoolSelector" nickname="Boolean" x="446.69991829204" y="945.798437362606" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>True</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="bca29ce5-ce63-4eff-bd07-9c238fe43f2c" start_index="0" end="a2236413-456b-482f-8f3c-010930df5503" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a2236413-456b-482f-8f3c-010930df5503" start_index="0" end="39739145-650e-4bf9-bb60-4174a90b494b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fdbafaad-160f-4c6a-b444-fdb676379957" start_index="0" end="39739145-650e-4bf9-bb60-4174a90b494b" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-10.3516321182251" eyeY="13.9155826568604" eyeZ="16.0006294250488" lookX="16.1289100646973" lookY="-8.16507530212402" lookZ="-20.5040168762207" upX="0.0538851283490658" upY="0.996194660663605" upZ="-0.0685019418597221" />
  </Cameras>
</Workspace>