<Workspace Version="1.1.0.2093" X="-1779.74098387148" Y="-3515.91707703539" zoom="1.10174311025718" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Color" resolvedName="DSCore.Color" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Display" resolvedName="Display.Display" assemblyName="Display.dll" />
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="02d610d6-c3ac-4e52-b19f-d546a45b8999" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Surface.Join" x="2316.73443878531" y="3256.72834402011" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Surface.Join@Autodesk.DesignScript.Geometry.Surface[]" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a33c42a3-bf25-41b3-b3d1-b38c3622f8d5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Surface.ByPatch" x="2102.71391652275" y="3397.54657893093" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Surface.ByPatch@Autodesk.DesignScript.Geometry.Curve" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3d28e711-9dbc-474a-aadd-6bcd8b9668f6" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.Extrude" x="2121.91391652275" y="3256.72834402011" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.Extrude@Autodesk.DesignScript.Geometry.Vector">
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="e891c91e-0d62-4a5a-a655-274d7f6c5cf8" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1648.34847928177" y="3205.28201292206" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="pt1 = Point.ByCoordinates(0,3,0);&#xA;pt2 = Point.ByCoordinates(1,4,0);&#xA;pt3 = Point.ByCoordinates(5,1,0);&#xA;pt4 = Point.ByCoordinates(3,0,0);&#xA;pts = {pt1, pt2, pt3, pt4};&#xA;&#xA;pCurve = PolyCurve.ByPoints(pts, true);&#xA;pCurveFillet = PolyCurve.Fillet(pCurve, 0.5);" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="4e5675c0-5e5a-4836-a8a6-195da837b123" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2571.00807864099" y="3256.72834402011" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="color = Color.ByARGB(200,141,198,217);&#xA;Display.ByGeometryColor(geometry, color);" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="02d610d6-c3ac-4e52-b19f-d546a45b8999" start_index="0" end="4e5675c0-5e5a-4836-a8a6-195da837b123" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a33c42a3-bf25-41b3-b3d1-b38c3622f8d5" start_index="0" end="02d610d6-c3ac-4e52-b19f-d546a45b8999" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3d28e711-9dbc-474a-aadd-6bcd8b9668f6" start_index="0" end="02d610d6-c3ac-4e52-b19f-d546a45b8999" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e891c91e-0d62-4a5a-a655-274d7f6c5cf8" start_index="6" end="3d28e711-9dbc-474a-aadd-6bcd8b9668f6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e891c91e-0d62-4a5a-a655-274d7f6c5cf8" start_index="6" end="a33c42a3-bf25-41b3-b3d1-b38c3622f8d5" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="1.32433915138245" eyeY="3.81142687797546" eyeZ="-6.24542427062988" lookX="-0.826950013637543" lookY="-3.06256794929504" lookZ="4.10514688491821" upX="-0.0796902775764465" upY="0.914959669113159" upZ="0.395598620176315" />
  </Cameras>
</Workspace>