<Workspace Version="1.2.1.3083" X="-106.36160426307" Y="-107.861295395542" zoom="1.55469255719439" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Color" resolvedName="DSCore.Color" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="cadf5f1c-ded7-4fa7-b446-4e2dfc6cf414" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Sheet.Views" x="629.466560365728" y="260.735220710077" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Views.Sheet.Views">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <DSRevitNodesUI.Categories guid="41c5e357-4c26-4ad4-a706-f895ecc73233" type="DSRevitNodesUI.Categories" nickname="Categories" x="162.23591940166" y="326.085761902188" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="422:Sheets" />
    <DSRevitNodesUI.ElementsOfCategory guid="39d28738-2d9c-4676-9343-066c035b51a1" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="364.263396430573" y="326.085761902188" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="41c5e357-4c26-4ad4-a706-f895ecc73233" start_index="0" end="39d28738-2d9c-4676-9343-066c035b51a1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="39d28738-2d9c-4676-9343-066c035b51a1" start_index="0" end="cadf5f1c-ded7-4fa7-b446-4e2dfc6cf414" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="fbaa394c-7960-4feb-9cac-68873497dba3" text="The Revit sample file can be found in Revit's installation directory, typically located in: &#xD;&#xA;&#xD;&#xA;C:\Program Files\Autodesk\Revit 2017\Samples" x="84.9088259540671" y="131.343505208871" />
  </Notes>
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="a887f384-6399-4c78-9d2c-bca2ad041c73" annotationText="Open with Revit file: rac_basic_sample_project.rvt" left="74.9088259540671" top="78.143505208871" width="289.6" height="140.8" fontSize="18" InitialTop="131.343505208871" InitialHeight="140" TextblockHeight="43.2" backgrouund="#FF48B9FF">
      <Models ModelGuid="fbaa394c-7960-4feb-9cac-68873497dba3" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-10.3516321182251" eyeY="13.9155826568604" eyeZ="16.0006294250488" lookX="16.1289100646973" lookY="-8.16507530212402" lookZ="-20.5040168762207" upX="0.0538851283490658" upY="0.996194660663605" upZ="-0.0685019418597221" />
  </Cameras>
</Workspace>