<Workspace Version="1.0.1.1167" X="-582.899416871889" Y="-455.192398751958" zoom="1.18583460520514" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <CoreNodeModels.Input.DoubleSlider guid="40cc063f-b11b-4aef-802a-e77b7bda24ea" type="CoreNodeModels.Input.DoubleSlider" nickname="Number Slider" x="523.507818406022" y="627.175607751742" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Double>10.1</System.Double>
      <Range min="0" max="100" step="0.1" />
    </CoreNodeModels.Input.DoubleSlider>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="86dfd2b1-88c1-43f5-96ab-f1e677f1fa6d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.Origin" x="524.351106327972" y="538.514240087986" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.Origin" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c013bf8b-ed73-4dd8-b706-3547e18180b3" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="BoundingBox.ByGeometry" x="1070.89191734539" y="545.761676087258" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.BoundingBox.ByGeometry@Autodesk.DesignScript.Geometry.Geometry" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="77d7e0d8-04d3-4cfa-9d95-b3c5d1b411d2" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Topology.Edges" x="1487.89333576751" y="426.904071711691" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Topology.Edges" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ee2f4d2b-7727-40f7-9a5b-e30c9170434e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Edge.CurveGeometry" x="1655.43419820015" y="427.218036800379" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Edge.CurveGeometry" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a331bf0e-e2c6-4654-aff5-668e46c23b7e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="BoundingBox.ToCuboid" x="1291.87402739495" y="427.42076937562" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.BoundingBox.ToCuboid" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="51e3ddab-2ccb-4f3a-82f0-3caa06014a8c" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Sphere.ByCenterPointRadius" x="864.406295486511" y="545.57781924752" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Sphere.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="dc725c3d-9830-41f2-9101-8e3d205ca256" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="BoundingBox.MinPoint" x="1291.87402739495" y="544.949743682416" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.BoundingBox.MinPoint" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a8bf3508-f70f-44ea-a900-624805a18eff" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="BoundingBox.MaxPoint" x="1292.84992995379" y="661.082148185153" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.BoundingBox.MaxPoint" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="40cc063f-b11b-4aef-802a-e77b7bda24ea" start_index="0" end="51e3ddab-2ccb-4f3a-82f0-3caa06014a8c" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="86dfd2b1-88c1-43f5-96ab-f1e677f1fa6d" start_index="0" end="51e3ddab-2ccb-4f3a-82f0-3caa06014a8c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c013bf8b-ed73-4dd8-b706-3547e18180b3" start_index="0" end="a331bf0e-e2c6-4654-aff5-668e46c23b7e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c013bf8b-ed73-4dd8-b706-3547e18180b3" start_index="0" end="dc725c3d-9830-41f2-9101-8e3d205ca256" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c013bf8b-ed73-4dd8-b706-3547e18180b3" start_index="0" end="a8bf3508-f70f-44ea-a900-624805a18eff" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="77d7e0d8-04d3-4cfa-9d95-b3c5d1b411d2" start_index="0" end="ee2f4d2b-7727-40f7-9a5b-e30c9170434e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a331bf0e-e2c6-4654-aff5-668e46c23b7e" start_index="0" end="77d7e0d8-04d3-4cfa-9d95-b3c5d1b411d2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="51e3ddab-2ccb-4f3a-82f0-3caa06014a8c" start_index="0" end="c013bf8b-ed73-4dd8-b706-3547e18180b3" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-35.3219742281043" eyeY="17.1688630036801" eyeZ="32.7516459921569" lookX="36.5177171103038" lookY="-14.7510849422642" lookZ="-34.4253505498032" upX="0.0507579899375084" upY="0.997564033955741" upZ="-0.0478496940900115" />
  </Cameras>
</Workspace>