<Workspace Version="1.3.0.875" X="-1299.36710151536" Y="-2916.99241957559" zoom="1.37012320340077" ScaleFactor="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <DSRevitNodesUI.ElementsOfType guid="7821a569-f5c4-42df-bdf9-c292994923f7" type="DSRevitNodesUI.ElementsOfType" nickname="All Elements of Type" x="1250.4798244813" y="2229.91667383983" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfType>
    <DSRevitNodesUI.ElementTypes guid="a047199f-14d5-489a-8634-ef3696ef65f0" type="DSRevitNodesUI.ElementTypes" nickname="Element Types" x="1027.65007190154" y="2229.91667383983" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="315:TopographySurface" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="87349f20-553f-42f8-92e7-0693a814e6c0" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Topography.Points" x="1495.96834522463" y="2229.91667383983" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Topography.Points">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7821a569-f5c4-42df-bdf9-c292994923f7" start_index="0" end="87349f20-553f-42f8-92e7-0693a814e6c0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a047199f-14d5-489a-8634-ef3696ef65f0" start_index="0" end="7821a569-f5c4-42df-bdf9-c292994923f7" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="34798.1805184776" eyeY="56753.7260889962" eyeZ="79496.5786522049" lookX="-48015.6117245182" lookY="-55193.72245555" lookZ="-38867.5250083801" upX="-0.38156118010428" upY="0.871213777978567" upZ="-0.308864928290916" />
  </Cameras>
</Workspace>